### ISSUE TITLE
"adiabatic_pop.txt" files not generated in example folder

### ISSUE THREAD

**Issue by bshralam** [bradenmweight/DFTBplus_Charge_Transfer#2]
Hello, 

I am trying to run the C60 example. Under the example/4_NAMD folder, I have run the NAMD jobs and they seem to have terminated normally. However, the 'get_average_DFTBplus.py' script is looking for 'adiabatic_pop.txt' files in each trajectory folder, which are missing.  

Each trajectory folder has the following:
band.out
B_q_zero.txt
charges.bin
detailed.out
dftb_in.hsd
dftb_pin.hsd
geom.out.gen
geom.out.xyz
md.out
namd.inp
namd.sbatch
output.log
output.slurm
results.tag

Thank you for your assistance, 
Bushra

**Comment by bradenmweight** [comment]
Hi Bushra,

I see that you have closed this issue. I'm glad you were able to solve the problem.

For completeness, what was the issue here ?

Best Wishes,

Braden
